### PR TITLE
fixup #775

### PR DESCRIPTION
**Pull request by gares**
that was clearly incomplete

### CODE REVIEW

**Comment by gares** [comment]
Such a ci job would have detected the author of the PR did introduce warnings (that happened to be errors)

**Comment by rtetley** [comment]
I agree, I'll take care of it. They merged the PR without the CI working anyways so... Should we go back to having a coq-master branch ?

**Comment by rtetley** [comment]
Something like #782 ?

**Comment by SkySkimmer** [comment]
IDK

**Comment by gares** [comment]
with this it works: https://github.com/ocaml/dune/pull/10631

**Pull request merged**
