### PR TITLE
Fix multi document feedback

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by maximedenes** [comment]
I can take care of rebasing if you like.

**Comment by gares** [comment]
Yes please rebase, I won't thouch this branch anymore today

**Comment by gares** [comment]
@maximedenes I did the rebase, and re-organized the tests into separate files.
But the framework still runs all of them in the same vscoq instance.

Can you help me run each file in a separate instance?

**Comment by maximedenes** [comment]
> Can you help me run each file in a separate instance?

It would be nice indeed, but let's open a separate issue, as it is going to be quite some work. Meanwhile, the tests are fine as they are IMHO.

**Pull request merged**
