### PR TITLE
Add color to more keywords

### LINKED ISSUE #298: Missing color for "Instance" and "Context" keyword
Coq "Context" and "Instance" keywords are not colored like other keyword (e.g. "Variable" and "Definiton").

Also of note : the brackets for record/instances `{|` and `|}` aren't colored properly, only the brace is colored, and not the vertical bar.

### PR DESCRIPTION
**Pull request by dlesbre**
This fixes #298 
Adds missing syntax colors to:
- keywords `Instance`, `Program Instance`, `Coercion`, `Context`, `Include`, `Search`, `Structure`, `Generalizable All`, `Generalizable Variables` `Existing Instance`, `Existing Class`, `Variant`, `About`, `Locate`, `Inline` (if after `Variable`, `Hypothese`,...), `Let Fixpoint`, `Let CoFixpoint`, `Canonical`, the `Obligation` commands, some `Proof` commands (`Save`, `Abort`, `Undo`, `Restart`, `Focus`...), `Implicit Types`, `Typeclasses Opaque`, `Typeclasses Transparent`
- control-flow keyword `fix ... for` and `where ... and`.
- brackets `{|` and `|}`
- types : `nat`, `bool`, `option`, `list`, `unit`,  `sum`, `prod`, `comparison`, `Empty_set`
- constructors : `tt`, `true`, `false`, `Some`, `None`, `S`, `O`, `inl`, `inr`, `pair`, `cons`, `Eq`, `Lt`, `Gt`, `id`, `ex`, `all` and `unique`.
- tactics : `transitivity`, `etransitivity`, `f_equal`, `exfalso`, `replace`, `tauto`, `cycle`, `swap`, `revgoals`, `cycle`, `shelve`, `unshelve`
- tactic keywords : `do` (move from tactic to keyword), `tryif` `once`, `at`, `only`
- snippets for `Infix`, `match`, `Class`/`Record`, `Instance`, `Existing Instance`, `Generalizable ...`, `pose`, `destruct` and `replace`
- fix `Variable (x: type).`, `Context {a: type}` and ``Context `{a:type}`` not coloring.
- fix `Inductive > foo` not coloring.
- Color identifiers when defining `Class` and `Record` similarly to `Inductive` 

This includes all changes from #279.

### CODE REVIEW

**Comment by thery** [comment]
Look good to me. If no reaction, I will merge it tomorrow

**Comment by Blaisorblade** [comment]
FWIW, highlighting "built-in types" has effects like
image

and there was already some concern in https://github.com/coq-community/vscoq/issues/298#issuecomment-1179045896. But on balance, this remains a net improvement that we can tweak later...

**Comment by thery** [comment]
@Blaisorblade can I merge?

**Comment by thery** [comment]
@dlesbre you are still doing some fixes I, great! Please tell me when you think it is ok and I will merge.

**Comment by dlesbre** [comment]
I've been adding missing stuff as I noticed it missing since I opened the PR. The last update were just somethings I noticed today. I think you can merge this now if you want too. 

I'll open a new PR if I find enough missing things to warrant that.

**Comment by thery** [comment]
@dlesbre Perfect. Thanks a lot!

**Pull request merged**
