### PR TITLE
[coq] Adapt to coq/coq#19193

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Review by gares — CHANGES_REQUESTED** [review]
Please use optcomp, ci fails on 8.19

**Comment by ejgallego** [comment]
Change is already inside a 8.20 conditional.

**Comment by rtetley** [comment]
It fails on coq-master which is normal since the coq pin hasn't changed in the flake.nix so it doesn't contain the latest change. Once https://github.com/coq/coq/pull/19193 is merged we beed to update the coq pin and it will be fine.

**Comment by SkySkimmer** [comment]
Please merge now

**Review by SkySkimmer — APPROVED** [review]

**Comment by rtetley** [comment]
Closing in favour of #778 
Pushed the changed there while fixing some opt comp flags

**Pull request closed without merging**
