### PR TITLE
Add a status bar item

### LINKED ISSUE #640: Viewing the VsCoq2 server executable and Coq version inside VS Code
Currently, the user can either specify the path to `vscoqtop`, or it can be read from path. In the latter case, since many people may have several opam switches, it's not obvious which executable was chosen, and if so, what the corresponding Coq version is.

Therefore, it would be useful to have the executable path and the Coq version (result of `vscoqtop --version`) displayed somewhere inside VS Code, e.g., in a panel or at least under extension settings. This is not only helpful for users themselves, but also when others are trying to help them debug some problem.

Another related problem, which deserves its own issue, is how to alternate between different opam switches/`vscoqtop`s from inside VS Code.

### PR DESCRIPTION
**Pull request by rtetley**
Add a status bar item to display vscoqtop info (version and coq version).
Closes #640

### CODE REVIEW

**Comment by rtetley** [comment]
@palmskog How do you feel about this for a display ? The large panel gets displayed on hover. Screenshot 2023-10-03 at 18 11 07

**Comment by thery** [comment]
@rtetley Are you planning to do a release soon or should we use master?

**Comment by rtetley** [comment]
@thery I was thinking of pushing for a release next week

**Comment by rtetley** [comment]
@palmskog I will address the opam stuff in a separate issue but this could work well for it indeed

**Pull request merged**
