### PR TITLE
Update screen capture and readme

### PR DESCRIPTION
**Pull request by rtetley**
Getting ready for vscoq 2 release I made a new set of screen captures and will update the readme.

### CODE REVIEW

**Comment by rtetley** [comment]
@gares @maximedenes What do you think of this new set of screenshots for the release ?

**Comment by gares** [comment]
The continuous checking gif is a bit odd(ly named).
You should that you can access any goal at any time, but you don't change the text and get continuous feedback on what you write. In some sense you could do the same screen capture in manual mode, don't you?

**Comment by gares** [comment]
Also, the font in the query panel is a bit funky to me. In any case, it is different from the other fonts, so you ask yourself why, but that is not the point of the demo ;-)

**Comment by rtetley** [comment]
> Also, the font in the query panel is a bit funky to me. In any case, it is different from the other fonts, so you ask yourself why, but that is not the point of the demo ;-)

Well that could be a mistake on my part... I'll check ! Thanks ;-)

**Comment by rtetley** [comment]
> You show that you can access any goal at any time, but you don't change the text and get continuous feedback on what you write. In some sense you could do the same screen capture in manual mode, don't you?

Makes sense. I'll update it to show continuous typing / feedback. 
Also I am going to cleanup the gifs / gif names before merging !

**Comment by rahulfromearth** [comment]
Hi @rtetley, What theme and font are you using in the gif? It looks aesthetic.

**Comment by rtetley** [comment]
Hi @rahulfromearth, thanks ! The theme is Purrp!, and the font is Cartograph CF. Cheers !

**Pull request merged**
