### PR TITLE
Adapt to coq/coq#18973.

### PR DESCRIPTION
**Pull request by rlepigre**

### CODE REVIEW

**Comment by rtetley** [comment]
Thanks !

**Comment by rlepigre** [comment]
@rtetley I had to rebase, I'm not sure what your `flake.lock` changes were about, but I had to drop them due to conflicts.

**Comment by rtetley** [comment]
Ah sorry, that was probably a mistake...

**Comment by proux01** [comment]
Upstream merged, please merge

**Comment by rtetley** [comment]
There is a release in progress, I will merge as soon as that is done.

**Comment by SkySkimmer** [comment]
ping @rtetley @gares

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@rtetley I believe you did block this branch for a reason. Can we release the lock and merge?

**Comment by rtetley** [comment]
I was waiting for https://github.com/ocaml/opam-repository/pull/26087 so that I can finalise the release process but after double checking I can unlock and perform the action from the tag later

**Comment by rtetley** [comment]
Ugh sorry I used the github interface to resolve a conflict which led to a merge of main into this branch... I preferred to fix it with a rebase

**Pull request merged**
