### PR TITLE
[VsCoq1] Server is webpacked.

### PR DESCRIPTION
**Pull request by vlj**
This PR webpacks the server component ; I didn't find a way to solve the issue with webpacking the client though.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
@maximedenes Did you forget to merge this or decide against it?

**Comment by maximedenes** [comment]
Oh, I forgot, sorry about that! I'll test a bit and will see how we can combine with #89.

**Comment by artagnon** [comment]
Can someone explain to me why this is a good idea? webpack adds extra bloat, along with a build-step. What does it buy us?

**Comment by maximedenes** [comment]
https://code.visualstudio.com/api/working-with-extensions/bundling-extension

**Comment by maximedenes** [comment]
IIRC, webpack made it simpler to load jQuery for the proof view. Note that utimately, the server should be replaced by a coq-side specific toplevel, so it does not matter so much.

**Comment by artagnon** [comment]
Nice. It's good for performance then.

**Comment by maximedenes** [comment]
> Nice. It's good for performance then.

Indeed. At least, that's what the recommendations say.

**Comment by fakusb** [comment]
I think webpacking should be a good idea, it seems strange that currently, my local build consists of 8MB for this plugin.

Does anyone have an Idea on the current state of this PR? I've not set up TS/JS build environments at all.

**Comment by thery** [comment]
This is superseded by #411

**Pull request closed without merging**
