### PR TITLE
add instructions for beta release and Coq 8.18+rc1

### PR DESCRIPTION
**Pull request by palmskog**
As requested by @maximedenes.

### CODE REVIEW

**Comment by maximedenes** [comment]
Thanks a lot for these improvements. Just one question: are you sure that pinning 8.18+rc1 is a good idea for end users? Won't it make the process less transparent for them once 8.18.0 is out?

**Comment by palmskog** [comment]
The README obviously needs to be changed once 8.18.0 is out. These instructions are to make it easier for people to get started with testing/running betas.

**Comment by palmskog** [comment]
Oh and specifically about the pinning: if you don't pin Coq to `8.18+rc1`, you will be prompted to upgrade to `coq.8.18.dev` now and then, which is probably not what anyone wants.

**Comment by maximedenes** [comment]
>  you will be prompted to upgrade to coq.8.18.dev now and then

Ah! I see, thanks!

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
