### PR TITLE
[vscoq1] fix https://github.com/coq/coq/pull/19040

### PR DESCRIPTION
**Pull request by thery**

### CODE REVIEW

**Comment by thery** [comment]
ok it seems to work

**Comment by thery** [comment]
@herbelin @jfehrle  I am interesting in an example that shows something that was  wrong and has been fixed.
Thanks

**Comment by herbelin** [comment]
I guess anything with an error should be noticeable, like `Check 1 1.`. You can also try if errors spanning over several lines are well-located.

I could make some tests too if you tell me how to test vscoq1 from a local archive.

**Comment by thery** [comment]
If you enable the extension VsCoq Legacy when using vscode, you should get the interface running

This following test seems ok 

ddd1

**Comment by Zimmi48** [comment]
Shouldn't there be a release or tag so that people find about the new version? Besides, the new version is only available on the Microsoft marketplace, not on Open VSX. Who is in charge of publishing new versions there?

**Comment by thery** [comment]
my bad! I did the [tag](https://github.com/coq-community/vscoq/releases/tag/v0.4.1). Unfornately it seems that I have not the right to publish it since it is under `coq-community`.
@rtetley can you do it or give me the right

**Comment by rtetley** [comment]
@thery just added you as a namespace owner !

**Comment by thery** [comment]
@rtetley Thanks!

The package has been published

**Pull request merged**
