### PR TITLE
Automated submission of OPAM package on release

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by gares** [comment]
This is what I do for coq-elpi, FTR:
```make
release:
	TAG=`git tag --sort=-v:refname|head -1`;\
	echo "Publishing tag $$TAG in suite $(OPAM_SUITE)";\
	echo "Hit ^C to stop, or type options (eg -n fro dry run) and return to continue:";\
	read OPTS;\
	opam-publish --tag=$$TAG --packages-directory=$(OPAM_SUITE)/packages \
		--repo=coq/opam-coq-archive -v $${TAG##v} $$OPTS \
		https://github.com/LPCIC/coq-elpi/releases/download/$$TAG/coq-elpi-$${TAG##v}.tar.gz
```

**Comment by gares** [comment]
I do upload by hand the tarball, since the one generated by github uses the gzip options of git which are going to change and invalidate the sha, while assets do not change hash.
I did not have the time to automate that using GH APIs, but should be doable.

**Comment by gares** [comment]
> I do upload by hand the tarball, since the one generated by github uses the gzip options of git which are going to change and invalidate the sha, while assets do not change hash. I did not have the time to automate that using GH APIs, but should be doable.

@maximedenes did you address this problem?

**Comment by maximedenes** [comment]
Yes, in #567.

**Pull request merged**
