### PR TITLE
Added option for _CoqProject location

### PR DESCRIPTION
**Pull request by fakusb**
added option to give relative path of _CoqProject-files if not at root of vscode-workspace

### CODE REVIEW

**Comment by fakusb** [comment]
ups, this might breaks with actually making use of -R/-Q options, I made this a draft and investigate further.

**Comment by artagnon** [comment]
Why not traverse up the directory tree until the project root directory, looking for `_CoqProject`? Otherwise, we have problems with making this new option point to a `_CoqProject` that's potentially in another project, no?

**Comment by fakusb** [comment]
I don't think it is a problem if the user is able to shoot himself into the foot by setting the variable wrong, as long as the plugin allows for more possible workflows.

Looking up automatically as a default would still be an improvement, as it allows for example multi-project workspaces, I might look into it. Maybe as the default option if the coqProjectPath is empty.

**Comment by fakusb** [comment]
I looked into it, and multiple coqProject-files in one workspace are more work than I'm willing to do.

Looking up the file for _CoqProject would also be nice, but the expedted time-spend to frustrated-user-time-saved ratio is not worth it for me.

So this PR won't alter anything more.
Still, thanks for the suggestion! If I wouldn't know that #140 will arrive at some time making all things done to the server obsolete, I would have thought more about it.

**Pull request merged**
