### PR TITLE
Files can now be reentered by coq after reopening

### LINKED ISSUE #155: Working with more than one Coq file does not work
Using VSCoq with just one Coq file open works reasonably well.
When I open a second Coq file it behaves fairly erratically. Some observable behavior:
- open file1.v + step down 1 step
- open file2.v + step down 1 step
- close file2.v
  * file1.v is gone (closed)
  * reopen file1.v shows that it has its state lost
  * step down in file1.v reopens file2.v
  * closing file2.v and reopen file1.v and step 1 step down again opens file2.v
  * As far as I can tell the only way out of this is to quit and reopen VSCode
- closing all open files before opening another one also doesn't help to avoid this.

In summary: I see now way to work with more than one Coq file except closing and reopening VSCode for each file.

### PR DESCRIPTION
**Pull request by fakusb**
Files can now be reentered by coq after reopening (while properly killing coqidetop)

Furthermore, files that had any interaction (goto cursor/end/position) that were only open as "preview" (single-click in explorer) files are promoted to "really open".

This improves on my former PR #167 and should close #155 and #120 .

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Sounds great! Follow-up question: can you check what happens if you close a file when coqidetop is crashed/stuck/...? Is the process still killed correctly? (Question inspired by all the times that Coq gets stuck and not interrupted correctly).

For a simple example:

```
Require Import Arith.

Lemma rewriteLoop (a b : nat) : a + b = 0.
Proof. rewrite !Nat.add_comm.
```

but you'll need a bigger file and async processing to get VsCoq in trouble.

**Comment by fakusb** [comment]
> can you check what happens if you close a file when coqidetop is crashed/stuck/...? Is the process still killed correctly? (Question inspired by all the times that Coq gets stuck and not interrupted correctly).

Sadly, the proofworker becomes an orphan process and continues to diverge in the background. I think this is a bug of coqidetop, as coqidetop gets terminated correctly.

**Comment by Blaisorblade** [comment]
That also sounds like an existing bug, I sometimes notice when those runaways when they eat too much memory.
But I thought somebody had fixed it by just sending a signal instead of also writing a message?

**Comment by fakusb** [comment]
I think you mean #127 , but that talks about the vscoq interrupt command.
the part I talk about, "disposing" coqtop in case of e.g. closing th editor, already uses SIGKILL. and coqidetop also receives the sigkill, as it dies. but it seems that coqidetop does not properly kill its proofworker that worked on the diverging tactic.

**Comment by Blaisorblade** [comment]
> the part I talk about, "disposing" coqtop in case of e.g. closing th editor, already uses SIGKILL. and coqidetop also receives the sigkill, as it dies. but it seems that coqidetop does not properly kill its proofworker that worked on the diverging tactic.

But coqidetop cannot handle SIGKILL to kill the proofworker, that’s not how SIGKILL works.

What about interrupting coqidetop (with the code in #127), then sending SIGTERM to tell coqidetop to clean up and exit? The only downside is if the clean up gets stuck, in which case SIGKILL is appropriate;
the POSIX semantics of sending SIGKILL to process P are basically to kill P with extreme prejudice, without letting P perform any cleanup. If any cleanup happens, that’s done by the OS.

In general, coqtop works well enough for Proof General, and coqidetop works well enough for CoqIDE — many of the VsCoq bugs are due to VsCoq sending the wrong commands (but probably not all). So if a solution is hard to find, checking what CoqIDE does might suggest solutions.

**Review by maximedenes — APPROVED** [review]
Looks like a nice improvement, thanks!

**Pull request merged**
