### PR TITLE
Fix #14: VsCoq's parser not coping with some notations

### LINKED ISSUE #14: vscoq parser is not coping with mathcomp/algebra/interval.v notations
```json
{
	"resource": "/home/ccohen/git/math-comp/master/mathcomp/algebra/interval.v",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "unterminated bracket '['",
	"source": "parser",
	"startLineNumber": 354,
	"startColumn": 43,
	"endLineNumber": 362,
	"endColumn": 14
}
```

Indeed vscode expects opening and closing brackets to match even if Coq parser would be ok with it, or even in comments (as @gares just showed me) !! e.g.
```coq
(* This is a smiley comment :) *)
```

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by maximedenes** [comment]
@gares This is probably going to break Elpi's quotations. I don't have enough experience with PEGJS to code your code with flexible delimiters (`{`, `{{`, `{{{`, etc), but a patch would be welcome. If you make `lp:` a keyword on Coq's side, we can even hardcode it in VsCoq.

**Comment by gares** [comment]
looks like pegjs has all the usual PEG arsenal, so I'll give it a try tomorrow. One thing you may help me is: how do you debug pegjs? (if you did already, otherwise I'll figure it out).

**Comment by gares** [comment]
This is a start, I played here https://pegjs.org/online and ". " does not terminate sentences when it is inside a  quotation, that can nest. I think the code below is even stronger than the one in Coq, so it needs to be weakened, but that is for tomorrow.
```js
{

// state, how lovely
var bound = "";
var nest = 0;

}

Main
 = Sentence Sentence
 / Sentence

Sentence
  = "lp:" q:Quote e:Sentence { return (q+e); }
  / ". " { return ". "; }
  / head:. e:Sentence { return (head+e); }
  
Quote
  = head:Open & { bound = head; nest++; return true } tail:Any { return (head + tail); }

Any
 = head:Closed & { return (head.length === bound.length) } & { return (nest === 1); } { return head; }
 / head:Closed & { return (head.length === bound.length) } & { nest--; return true } rest:Any { return (head + rest); }
 / head:Closed rest:Any { return (head + rest); }
 / head:Open & { return (head === bound); } & { nest++; return true } rest:Any { return (head + rest); }
 / head:Open rest:Any { return (head + rest); }
 / head:. rest:Any { return (head + rest); }
  
Open
 = "{" Open { return (text()); }
 / "{"      { return (text()); }
 
Closed
 = "}" Closed { return (text()); }
 / "}" { return (text()); }
```

**Comment by gares** [comment]
Oh, the state thing sucks, but I'm not the only one that thought about it: https://github.com/pegjs/pegjs/issues/45

**Pull request merged**
