### PR TITLE
Document manager

### PR DESCRIPTION
**Pull request by maximedenes**
This PR makes VsCoq use Coq's document manager (https://github.com/coq/coq/pull/12461) instead of adapting the CoqIDE protocol. This is very much work in progress.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
I understand this effort will flow into a different repository? Hence, I'm tentatively closing it — happy to reopen at the drop of a hat 😄 .

**Comment by gares** [comment]
Hum, I thought this branch was in coq CI

**Comment by SkySkimmer** [comment]
It is

**Comment by gares** [comment]
ok, we will reopen it eventually

**Comment by SkySkimmer** [comment]
reopening so I can push using my coq-community powers

**Comment by SkySkimmer** [comment]
done

**Comment by Blaisorblade** [comment]
I see, let's just keep open.

**Comment by maximedenes** [comment]
Was removed from Coq's CI, so we can now close.

**Pull request closed without merging**
