### PR TITLE
[VsCoq2] Change tmLanguage xml file to tmLanguage.json file

### PR DESCRIPTION
**Pull request by Hjaltesorgenfrei**
Seems to be what was intended from previous change as it was renamed in package.json.
But the file was not renamed or changed to json file, so Highlighting broke.

Calling the file `coq.tmLanguage.json` seems to be the default as seen here: <https://github.com/microsoft/vscode/blob/main/extensions/json/syntaxes/JSON.tmLanguage.json>

### CODE REVIEW

**Comment by Hjaltesorgenfrei** [comment]
@rtetley @maximedenes I see that you changed it back, should we just close this pr without merging it?

**Comment by maximedenes** [comment]
@Hjaltesorgenfrei Sorry, I had missed this PR. I like the change, will review it asap. Let's keep it open!

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
I'll try to rebase on `main`, let's see what happens.

**Comment by maximedenes** [comment]
Grrr, same effect, unfortunately. I'll reopen a PR for your branch.

**Pull request closed without merging**
